service: toggl-sync-timesheet-v2

provider: 
  memorySize: 256
  name: aws
  runtime: nodejs14.x
  versionFunctions: true

plugins: 
  - serverless-dotenv-plugin

functions: 
  toggl_sync: 
    handler: 'handler.sync'
    events: 
      - 
        schedule: 
          enabled: false
          rate: cron(0 0 * * ? *)
    
  toggl_refresh:
    handler: 'handler.refresh'
    events: 
      - 
        schedule: 
          enabled: true
          rate: cron(0/15 9-18 ? * MON-FRI *)

  myhours_sync:
    handler: 'handler.myhours_sync'
    events: 
      - 
        schedule: 
          enabled: false
          rate: cron(0 0 * * ? *)
  
  #toggl_stop:
  #  handler: 'handler.stopper'
